/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class school21_smartcalc_application_smartcalc_HelloController */

#ifndef _Included_school21_smartcalc_application_smartcalc_HelloController
#define _Included_school21_smartcalc_application_smartcalc_HelloController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     school21_smartcalc_application_smartcalc_HelloController
 * Method:    Calculate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_school21_smartcalc_application_smartcalc_HelloController_Calculate
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
